### PR TITLE
Extended sensor support

### PR DESCRIPTION
**Pull request by ddawley**
Hi @rsnodgrass,

Here are the changes we discussed briefly yesterday?  I took a slightly different approach as it allowed me to keep all the changes in hass-sensorpush and leave pysensorpush alone.

### CODE REVIEW

**Comment by rsnodgrass** [comment]
What is type "HTP.xw"?  Your change in removed checking supported_measurements and wanted to better understand why.

**Comment by ddawley** [comment]
Hi Ryan,

"HTP.xw" is the type reported by the only sensor that support "barometric_pressure". All types support the other four measures.

Best Regards

Dave Dawley
-----Original Message-----

**Comment by rsnodgrass** [comment]
Only change that is NOT clear to the reader is this change from:

            if measure in supported_measurements:

to:

            if sensor_info.get('type') == 'HTP.xw' or measure != MEASURE_BAROMETRIC_PRESSURE:

This is NOT clear to the casual reader what is going on. I will merge your change, but why is it not possible to include MEASURE_BAROMETRIC_PRESSURE in supported_measurements so that the original simple to understand check is used?

**Comment by ddawley** [comment]
I agree with you.  I can extract that code into a method if you like.  I have prototyped the method "get_supported_measurements".  It does not use calibrations since that will always only return temperature and humidity.  Instead I'm using a samples query and checking the returned sensor keys for the equivalent MEASURE keys.  It is OK to request measurements that a sensor does not support, so I request everything and then inventory what comes back:

def get_supported_measurements(sensorpush, sensor_info):
    measure_keys = list(MEASURES.keys())
    sensor_id = sensor_info['id']
    params = {'limit':1, 'sensors':[sensor_id], 'measures': measure_keys}

    #query sensor for supported measurements
    sample_value = sensorpush.query(method='POST', url=QUERY_SAMPLES_ENDPOINT, extra_params=params)
    sensor_keys = list(sample_value['sensors'][sensor_id][0].keys())

    supported_measurements = []

    for key in measure_keys:
        if sensor_keys.count(key) == 1:
            supported_measurements.append(MEASURES[key])

    return supported_measurements

This also would allow use of "FOR measure in supported_measurements:" and eliminate the need for the IF within the FOR

If you think this is worth doing I will be happy to push it.

Best Regards

Dave Dawley
-----Original Message-----

**Pull request merged**
